"""Pure helpers to generate a VUnit run script (no I/O, unit-testable)."""

from __future__ import annotations

from .parsing import is_vunit_builtin

VHDL_EXTS = (".vhd", ".vhdl", ".vho", ".vhy")
VERILOG_EXTS = (".v", ".sv")


def languages(entries: list[tuple[str, str]]) -> set[str]:
    """Languages present among the entries' file extensions."""
    langs = set()
    for _, path in entries:
        if path.lower().endswith(VHDL_EXTS):
            langs.add("vhdl")
        elif path.lower().endswith(VERILOG_EXTS):
            langs.add("verilog")
    return langs


def entries_from_export(data: dict) -> list[tuple[str, str]]:
    """(library, path) entries from a --export-json payload, in compile
    order, with VUnit built-in library files dropped (they are re-added
    via add_vhdl_builtins()/add_verilog_builtins())."""
    seen: set[tuple[str, str]] = set()
    entries: list[tuple[str, str]] = []
    for f in data.get("files", []):
        path, lib = f.get("file_name", ""), f.get("library_name", "work")
        if not path or is_vunit_builtin(path):
            continue
        if (lib, path) not in seen:
            seen.add((lib, path))
            entries.append((lib, path))
    return entries


def render_run_py(entries: list[tuple[str, str]]) -> str:
    """Render a run.py registering the given (library, path) entries in
    order. Test cases are left to VUnit's automatic testbench discovery."""
    langs = languages(entries)
    libs: dict[str, list[str]] = {}
    order: list[str] = []
    for lib, path in entries:
        if lib not in libs:
            libs[lib] = []
            order.append(lib)
        libs[lib].append(path)

    lines = [
        "#!/usr/bin/env python3",
        '"""VUnit run script generated by vunit-mcp (vunit_scaffold)."""',
        "from vunit import VUnit",
        "",
        "vu = VUnit.from_argv(compile_builtins=False)",
    ]
    if "vhdl" in langs:
        lines.append("vu.add_vhdl_builtins()")
    if "verilog" in langs:
        lines.append("vu.add_verilog_builtins()")
    for lib in order:
        lines.append(f"{lib} = vu.add_library({lib!r})")
        files = ",\n    ".join(repr(p) for p in libs[lib])
        lines.append(f"{lib}.add_source_files(\n    {files},\n)")
        lines.append("")
    lines.append("vu.main()")
    return "\n".join(lines) + "\n"
